# Generated by Django 4.1.7 on 2023-04-11 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageDateTime', models.DateTimeField(auto_now_add=True)),
                ('messageTitle', models.CharField(max_length=50)),
                ('messageText', models.TextField()),
                ('messageImage', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('messageVideo', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('messageCategory', models.CharField(choices=[('TANK', 'танки'), ('HEAL', 'лекари'), ('DDEA', 'воины'), ('MERC', 'торговцы'), ('GUIL', 'гильдмастеры'), ('QUES', 'квестгиверы'), ('BLSM', 'кузнецы'), ('TANN', 'кожевники'), ('POTM', 'зельевары'), ('SPEL', 'мастера_заклинаний')], default='DDEA', max_length=4)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postText', models.TextField()),
                ('postAccepted', models.BooleanField(default=False)),
                ('postDateTime', models.DateTimeField(auto_now_add=True)),
                ('postAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postToMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.message')),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('codeDateTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
